---
title: "Data Request Memo"
author: "Division of Data, Assessment, and Research"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(tidyverse)
library(lubridate)
library(httr)
library(xml2)
library(rvest)
library(odbc)
library(DBI)
library(curl)
library(blastula)
api_key = readRegistry("Environment", hive = "HCU")$quickbase_api_key
api_pwd = readRegistry("Environment", hive = "HCU")$quickbase_pwd
api_uid = readRegistry("Environment", hive = "HCU")$email_address
api_app = readRegistry("Environment", hive = "HCU")$quickbase_api_token
url = readRegistry("Environment", hive = "HCU")$quickbase_api_url

granted_dbs = GET(
  str_c(
    url,
    "?a", "=", "API_GrantedDBs", # API_GrantedDBs function,
    "&", "usertoken", "=", api_key # use API user key to authenticate (could also use ticket)
  )
) %>% 
  content()

## Create a tibble and extract names and IDs from API
db = tibble(
  db_name = xml_nodes(granted_dbs, "dbname") %>% 
    str_flatten() %>% 
    str_split("</dbname><dbname>") %>% 
    unlist(),
  db_id = xml_nodes(granted_dbs, "dbid") %>% 
    str_flatten() %>% 
    str_split("</dbid><dbid>") %>% 
    unlist() 
) %>% 
  ## Concatenate to match QuNect naming conventions
  mutate(
    db_name = str_replace_all(db_name, "</dbname>", "") %>% 
      str_replace_all("<dbname>", "") %>% 
      str_replace_all("[ :]", "_"),
    db_id = str_replace_all(db_id, "</dbid>", "") %>% 
      str_replace_all("<dbid>", ""),
    db_name_id = str_c(db_name, db_id, sep  = "_")
  ) 

con = dbConnect(
  odbc(), 
  "QuickBase via QuNect user",
  timeout = 10
)

# Query database 
memo_data = left_join(
  # Requests table
  dbGetQuery(
    con,
    str_c(
      "select *
    from ",
      db$db_name_id[str_ends(db$db_name, "__Requests")]
    )
  ) %>% 
    janitor::clean_names(),
  # Status table
  dbGetQuery(
    con,
    str_c(
      "select *
    from ",
      db$db_name_id[str_detect(db$db_name, "Status")]
    )
  ) %>% 
    janitor::clean_names() %>% 
    arrange(request_id, desc(date_modified)) %>% 
    group_by(request_id) %>% 
    summarize_at(vars(file_location:other_data_sharing_mechanism), "first") %>% 
    ungroup(),
  # Keys
  by = c("record_id" = "request_id")
) %>% 
  as_tibble() %>% 
  filter(case_status == "Pending PII Approval")
```
---
params: 
  req: `r req`
---

***
__TO__: Hanseul Kang, Superintendent

__THROUGH__: Rebecca Lamury, Assistant Superintendent, DAR

__FROM__: Evan Kramer, Director of Research, Analysis, and Reporting, DAR and `r str_replace(memo_data$data_request_manager[req], "@dc.gov", "") %>% str_replace("[.]", " ") %>% str_to_title()`, Data Analysis Manager

__RE__: Requesting Approval for Data Request to be Fulfilled

__DATE__: `r str_c(month(now(), label = T, abbr = F), " ", day(now()), ", ", year(now()))`

***

Please review and let me know if you can approve the following data request fulfillment.

- The data were requested by: `r memo_data$requester_full_name[req]`, `r ifelse(!is.na(memo_data$requesting_organization_final[req]), memo_data$requesting_organization_final[req], ifelse(memo_data$requesting_organization[req] == "Other", memo_data$other_organization[req], memo_data$requesting_organization[req]))`
- The end recipient of the data is: `r print("recipient")`
- The data were requested on: `r str_c(month(memo_data$date_created[req]), day(memo_data$date_created[req]), year(memo_data$date_created[req]), sep = "/")`
- The stated purpose of the data request is: `r memo_data$purpose_of_data_request[req]`
- The data we propose to release are: `r print("kable")`
- The data have been prepared by `r str_replace(memo_data$data_request_analyst[req], "@dc.gov", "") %>% str_replace("[.]", " ") %>% str_to_title()` and checked by `r str_replace(memo_data$data_request_qa[req], "@dc.gov", "") %>% str_replace("[.]", " ") %>% str_to_title()`. These people verify that: 
    - They will transfer data via `r ifelse(!is.na(memo_data$other_data_sharing_mechanism[req]), memo_data$other_data_sharing_mechanism[req], memo_data$data_sharing_mechanism[req])`.